-- App redesign (Dalfen design handoff, Oct 2026).
--
-- 1. deals.ref: a short human id ("D-1042") for breadcrumbs, share sheets and
--    the IC slide footer. URLs keep the uuid; /deals/D-1042 redirects.
-- 2. Dates the summary's "Next dates" card and the /ic hub need.
-- 3. In-place rent, for the Rent Upside flag. Stored in the basis it was
--    quoted in, exactly like comps.rent / comps.rent_basis.
-- 4. deal_signals: the six site-viability flags behind the site score. Each
--    row holds what Hopper computed (auto_*) and an optional human override
--    (override_*); the override wins when present. The order the app shows
--    them in is fixed: demand, zoning, access, site, basis, rent.
-- 5. Site-visit notes: a new activity type plus attached photo paths.

alter table deals add column if not exists ref bigint generated by default as identity (start with 1001);
create unique index if not exists deals_ref_key on deals(ref);

alter table deals add column if not exists ic_on date;
alter table deals add column if not exists loi_response_due_on date;
alter table deals add column if not exists phase1_ordered_on date;
alter table deals add column if not exists in_place_rent numeric;
alter table deals add column if not exists in_place_rent_basis text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'deals_in_place_rent_basis_check') then
    alter table deals add constraint deals_in_place_rent_basis_check check (
      in_place_rent_basis is null or in_place_rent_basis in
        ('per_acre_monthly','per_sf_bldg_monthly','per_sf_bldg_annual','per_sf_land_monthly','total_monthly'));
  end if;
end $$;

create table if not exists deal_signals (
  deal_id uuid not null references deals(id) on delete cascade,
  key text not null check (key in ('demand','zoning','access','site','basis','rent')),
  auto_state text check (auto_state in ('strong','watch','weak','unknown')),
  auto_note text,
  auto_source text,
  auto_detail jsonb,
  auto_at timestamptz,
  override_state text check (override_state in ('strong','watch','weak')),
  override_note text,
  override_by text,
  override_at timestamptz,
  primary key (deal_id, key)
);
alter table deal_signals enable row level security;
revoke all on deal_signals from anon, authenticated;
grant all on deal_signals to service_role;

-- activities.activity_type gains 'site_visit'. The original check was inline
-- and unnamed, so find it by definition rather than guessing its name.
do $$
declare c text;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'activities'::regclass and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%activity_type%'
  loop
    execute format('alter table activities drop constraint %I', c);
  end loop;
  alter table activities add constraint activities_activity_type_check check (
    activity_type in ('call','email','meeting','tour','note','site_visit','other'));
end $$;

alter table activities add column if not exists photo_paths text[] not null default '{}';
